### ISSUE TITLE
PIN'ler ve breadboard hakkında

### ISSUE THREAD

**Issue by ShnAhmet** [zafersn/WiFi-RC-Controller-With-Camera#13]
1 adet L298N motor sürücü, 1 adet LM2596 güç kaynağı 5v, tank şasi (2 adet dc motor üzerinde mevcut), raspberry pi3 (wifi ve bluetooth üzerinde), 1 adet arducam, 12v lipo batarya, jumper kablolar, 2 adet servo motor....yani her şey tamam görünüyor. Sizin Pi_CAR programı da telefonumda yüklü..Tank modeliniz 6 motorlu, oradan bakıp yapmaya çalıştım ama beceremedim. Rasp ile telefonum arasında bağlantı kurulduğunu düşünüyorum ama joystick ekran modelinizin ana görüntüsü dışında başka bir şey yok. Rasp PIN girişleri ve breadboard ayarlarını gösteren bir şemaya ihtiyacım var. Yardımcı olabilir misiniz?

**Comment by zafersn** [comment]
Selam @ShnAhmet .  Raspberry pi pin bağlantı şeması için şu linki denedin mi ?

![image](https://user-images.githubusercontent.com/13236364/37558771-49300b38-2a2a-11e8-9cc0-f68c3a34d871.png)

![image](https://user-images.githubusercontent.com/13236364/37558773-56a79970-2a2a-11e8-85ff-40b81050382a.png)
 
Şimdi öncelikle android program ile raspberry nin birbirine bağlandığına emin olmalıyız. İlk önce şuna bakalım. Android Telofonunuzun WiFi bölümünde Raspberry pi SSID 'sini görüp ona bağlanıyormusnuz ? eğer bağlanmış iseniz. 
Data göndermeyi deneyin. Rasbperry pinizi bir ekrana bağlandığınızda dataların geldiğini görmelisiniz.

**Comment by ShnAhmet** [comment]
Lipodan LM2576 ya baglanti ayni.breadboarddaki servo motor baglantilari ve rasp baglantisi, servosan raspa baglantilar da ayni.raspin guc kaynagi baglantisi da tamam ama sizdeki 4 pil yani 6v, bendeki ise 6 pil yani 9v. Buraya kadar ok. Bundan sonrasinda olayin sikintili kismi bence: L298N motor surucunun de harici guc kaynagina bagladim.dedigim gibi sizin baglanti semaniz anladigim kadariyla 2 adet bts7960 surucu mantigina gore kurulu bana ise tek bir L298N ile 2 dc motor baglantisini dogru yapmaya calismak. bunun rasp pinlerine giris cikis baglanti şeması. PiCar ile Wifi baglanti kontrolunu ise yarin yapacagim su an ekranda bir sikintim var.

Yani kisaca:
1) raspin guc kaynagi illa 4 pilden mi olusmaliydi?
2) L298N motor surucumu bir harici guc kaynagina baglamam yanlis mi? Ve rasp ile baglanti semasi ne olmali?

**Comment by zafersn** [comment]
@ShnAhmet  raspberry 'e 9v veremezsin.  :( 5V Vermek zorundasın. Raspberr' in çalışıuyor mu ? Ekrana taktığında görüntü gelip gelmediğini kontrol et.

Şimdi l298 motor sürücü bağlantını da şöyle yapmalısın. Sende 4 adet pwm girisi var l298 'in üzerinde ki EN - Pinlerini jumpjer ile 5v 'a kısa devre yap VE IN1, IN2, IN3 ,IN4 E raspberry 'nin pwm pinlerini tak yani
GPIO12, GPIO18, GPIO13, GPIO19. Yukarıdaki BTS7960 Motor sürcüsüne taktığım pwm 'leri sen l298 'in IN pinlerine takacaksın.

Birde harici güç kaynağı olursa mutlaka Güç kaynaklarının GND pinlerini ortak yapmalısın.

![image](https://user-images.githubusercontent.com/13236364/37563898-d1bef042-2a9b-11e8-91ba-f23d8dce253b.png)

**Comment by ShnAhmet** [comment]
Dediklerinizi uyguladim. ena ve enb leri 5v lari ile jumperladim. IN1,2,3,4 u sirasiyla gpio 12,18,13,19 pinleriyle birlestirdim. Motor surucuye harici guc kaynagi bagladigim icin surucunun gnd sinden raspin gnd sine baglanti da cektim..
Sonuc: kamera ve servolar calisiyor yani telefonumdan kontrol ediliyor ama dc motorlar hareket etmiyor.

**Comment by zafersn** [comment]
DC motor surucun sağlam de mi?  
Kaç V ile besliyorsun surucuyu? 
Voltmetre ile sürücünün çıkışlarını ölçer misin ileri geri hareket tuşlarına basiliyken bakalım çıkış verio mu?
Son olarak in1-2-3-4 e taktiğin pinlerin yerini değiştirerek deneyebilirmisin.?

**Comment by ShnAhmet** [comment]
Problem motor surucude çıktı. Su an sistem calisiyor. Tesekkur ederim.

**Comment by zafersn** [comment]
Ben teşekkür ederim kolay gelsin, başarılar.

**Comment by ShnAhmet** [comment]
Tekrar selam. Deamon tools ile ".img" uzantili dosyanizi acip kodlara gozatmak istedim ama mumkun olmadi. Gercekten cok merak ediyorum. Kodlariniza nasil ulasabilirim? Ne onerirsiniz?

**Comment by zafersn** [comment]
selam @ShnAhmet. img dosyasını çıkartarak kodlara ulaşmazsın. kod dosyasına ulaşabilirsin ama ben oraya kodları .pyc  yani derlenmiş python koduna ulaşabilirsin, oda senin işine yaramaz. Yaklaşık 2Hafta önce raspberry pi için kaynak kodları yayınladım. Buradan ulaşabilirsin.

https://github.com/zafersn/WiFi-RC-Controller-With-Camera/tree/master/T%C3%9CRK%C3%87E/V3/Raspberry%20Pi%20Kaynak%20Kodu

Raspberry pi açılışta otomatik olarak rc-car control uygulaması ile başlar. Eğer bu uygulamadan çıkmak istiyor ve komut satırı ekranına ulaşmak için benzer bir soru burada sordular ve cevapladım. Cevaba ulaşmak için . 

https://github.com/zafersn/WiFi-RC-Controller-With-Camera/issues/12#issuecomment-366960902

**Comment by ShnAhmet** [comment]
Hizli reaktiviten icin tesekkurler..
