### ISSUE TITLE
V1 and V3 

### ISSUE THREAD

**Issue by anakjid** [zafersn/WiFi-RC-Controller-With-Camera#15]
About V1, using arduino nano to control dc motor dirive. 
Its mean V3, just used rasperry pi only? for wifi, anndroid apps and motor controller?
Please give me details on the circuit of the project if using only Raspberry pi to do all those work

**Comment by zafersn** [comment]
Hi @anakjid  . The V1 version of the android control application has now been removed from the Google Play Market. the documents belonging to this version of repository V1 are kept only for information purposes.  All necessary documentation for version V3 is available. For circuit connection diagram, see: https://github.com/zafersn/WiFi-RC-Controller-With-Camera/blob/master/ENGLISH/V3/select_Vehicle_en.md

There are 2 types of vehicles here. Check the circuit diagrams according to the type of vehicle you will select.

**Comment by anakjid** [comment]
thank you for your feedback. MAy I know if I want to use the V3 method but using DC gear Motor and with the function of V1, is it posibble? I just want to design the wifi RC controller with camera using raspberry pi only without arduino nano. is it possible?

**Comment by zafersn** [comment]
In V3 version you can only design wifi RC controller with camera using raspberry. Without Arduino nano. The v3 version is more stable and has more features.
