### ISSUE TITLE
Raspbery pi Zero ile çalışması hakkında

### ISSUE THREAD

**Issue by onuratakan** [zafersn/WiFi-RC-Controller-With-Camera#18]
Öncelikle muhteşem bir proje olmuş elinize sağlık. Ben bu projeyi Pi Zero w ile yapmak istiyorum malum daha uygun ama çalışır mı bilmiyorum beni bu konuda bilgilendirebilirmisiniz.

**Comment by zafersn** [comment]
merha @atakan06 . güzel yorumunuz için teşekkür ederim. Pi Zero w inceledim. Çalışmaması için hiç bir neden yok. Gördüğüm kadarıyla pin dizilimleri de aynı. Size tavsiyem. image kurulumunu yaptıkdan sonra android uygulamayı satın almadan önce ücretsiz windows uygulaması ile test etmeniz. Hatta isterseniz, raspberry pi python kodlarını paylaştım. Kendinizde geliştirme yapabilirsiniz.
