### ISSUE TITLE
Kamera çesitleri hakkında

### ISSUE THREAD

**Issue by onuratakan** [zafersn/WiFi-RC-Controller-With-Camera#19]
merhaba bütçenin kısıtlı olması nedeniyle pi zero ile kullanacağım bu kameranın projede çalışıp çalışmadığını merak ediyorum.
https://urun.n11.com/diger/raspberry-pi-zero-v13-kamera-P266490836?gclid=CjwKCAjw7vraBRBbEiwA4WBOn8cvAqQYATvN7pZ2vejwaETI69HEFYVAvmBtlfZksVThZii0hkAI6hoCxPwQAvD_BwE

**Comment by zafersn** [comment]
Evet calisir bu kamera
