### ISSUE TITLE
renkli ekran ve yıldırım simgesi

### ISSUE THREAD

**Issue by ahmetkorkmaz82** [zafersn/WiFi-RC-Controller-With-Camera#23]
sd kartı takıp raspberry model 3b+ güç verdiğimde 4 renkli bir splash ekran ve sağ üstte sarı yıldırım simgesi görünüyor ve açılmıyor.

**Comment by zafersn** [comment]
Merhaba @ahmetkorkmaz82 .  Kullandığın güç kaynağıyla ilgili olabilir. Tavsiye edilen güç kaynağı 5v 2A 'lik bir güç kaynağı. Sizin güç kaynağı değerleriniz nedir?

**Comment by ahmetkorkmaz82** [comment]
Hızlı cevabınız için teşekkürler. Yukarıdaki mesajı yazmadan önce internette araştırdığımda güç kaynağı ile ilgili olabileceğini öğrenmiştim ancak değişik değerdeki güç kaynaklarıyla denememe rağmen çalışmadı. Ayrıca da raspberry pi yi daha önce bu denediğim güç kaynaklarıyla çalıştırmıştım. Hatta daha sonra güncel raspbian işletim sistemini kurduğumda yine çalıştı. Ben de güncel raspbian işletim sisteminde sizin paylaştığınız kaynak kodu çalıştırmaya çalıştım o da olmadı sanırım statik ip vermek gerekiyor. Ya da başka bir şeyi atlıyorum.

**Comment by zafersn** [comment]
> Hızlı cevabınız için teşekkürler. Yukarıdaki mesajı yazmadan önce internette araştırdığımda güç kaynağı ile ilgili olabileceğini öğrenmiştim ancak değişik değerdeki güç kaynaklarıyla denememe rağmen çalışmadı. Ayrıca da raspberry pi yi daha önce bu denediğim güç kaynaklarıyla çalıştırmıştım. Hatta daha sonra güncel raspbian işletim sistemini kurduğumda yine çalıştı. Ben de güncel raspbian işletim sisteminde sizin paylaştığınız kaynak kodu çalıştırmaya çalıştım o da olmadı sanırım statik ip vermek gerekiyor. Ya da başka bir şeyi atlıyorum.

WiFi-RC-Controller-With-Camera Version 3 'ü kullanıyorsunuz değil mi?
https://github.com/zafersn/WiFi-RC-Controller-With-Camera/tree/master/T%C3%9CRK%C3%87E/V3

Emin olmamak la beraber bu konuyla ilgili olarak size akşam dönüş yapmaya çalışacağım. Bu proje yayınladıkdan sonra üzerinden çok uzun bir zaman geçti. Proje Rasbian ' ın  Raspbian Stretch Lite  image ' ı üzerine kurdum diye hatırlıyorum. yani desktop ekranının açılmaması gerekir.
