### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by YXCXL** [zafersn/WiFi-RC-Controller-With-Camera#24]
Merhaba Zafer abi öncelikle projenizi çok beğendim kendi android raspberry kontrol uygulamamı yapma niyetindeyim fakat tecrübesizim kaynak yahut yardımcı döküman ihtiyacım var yardımcı olurmusunuz.

**Comment by zafersn** [comment]
Merhaba @YXCXL  teşekkür ederim. Elimden geldiğince yardım etmeyi isterim. Bu proje için yardıma ihtiyacın olursa hiç çekinmeden sorabilirsin.

**Comment by YXCXL** [comment]
Size ulaşabileceğim herhangi bir platform mevcutmu eposta ile ulaşmayı denedim ama.

**Comment by zafersn** [comment]
@YXCXL Buradan ulaşabilirsin. Hem seninle aynı problemi yaşayanlar senin sorularından, çözümlerinden faydalanmış olur.

**Comment by YXCXL** [comment]
Öncelikle imajda kullanılan framework, stream vs kullanılan yazılımlar hakkında bilgi alabilirmiyim projeyi kendim yapıp webview olarak kontrol etmek istiyorum v1 ve v2deki gibi arduino kullanmakta istemiyorum birçok projeyi inceledim fakat ayrıntılı bilgi kaynak edinemedim kitap öneriniz vs varsa almak isterim çok teşekkürler

**Comment by zafersn** [comment]
Raspbian Stretch Lite image olarak kullandım [Buradan ulaşabilirsin](https://www.raspberrypi.org/downloads/raspbian/)

raspberry pi için kaynak kodlarını paylaştım: [Burada](https://github.com/zafersn/WiFi-RC-Controller-With-Camera/tree/master/T%C3%9CRK%C3%87E/V3/Raspberry%20Pi%20Kaynak%20Kodu)

Gorüntü aktarımı için Gstreamer kütüphanesini kullandım. Android ile Raspberry pi arasında. 
Kontrol komutlarını(sağa sola dön vs...) aktarmak için udp/ip haberleşmesi var. 
Raspberry Pide codlar python ile Androidde ise java+cpp(NDK) ile yazıldı.
Şİmdilik aklıma gelenler bunlar.

**Comment by YXCXL** [comment]
Çok teşekkürler projelerinizde başarılar dilerim.

**Comment by ugurcandede** [comment]
> Raspbian Stretch Lite image olarak kullandım [Buradan ulaşabilirsin](https://www.raspberrypi.org/downloads/raspbian/)
> 
> raspberry pi için kaynak kodlarını paylaştım: [Burada](https://github.com/zafersn/WiFi-RC-Controller-With-Camera/tree/master/T%C3%9CRK%C3%87E/V3/Raspberry%20Pi%20Kaynak%20Kodu)
> 
> Gorüntü aktarımı için Gstreamer kütüphanesini kullandım. Android ile Raspberry pi arasında.
> Kontrol komutlarını(sağa sola dön vs...) aktarmak için udp/ip haberleşmesi var.
> Raspberry Pide codlar python ile Androidde ise java+cpp(NDK) ile yazıldı.
> Şİmdilik aklıma gelenler bunlar.

Gstreamer dan başka kütüphane kullandınız mı? 
Sanırım Python sürümü olarak da 2.7 kullanmışsınız doğru mudur?
Hali hazırda çalışan Raspberry Pi3 cihazımda kodları çalıştırmak istiyorum.

**Comment by zafersn** [comment]
@ugurcandede  
sadece Gstreamer yeterli 
Bizim uygulamalarımız için 2.7 kullandım diye hatırlıyorum.
Bun uygulamanın hepsi pi3 de test edildi. Pi3 üzerinde çalıştırabilirsiniz
