### ISSUE TITLE
Would like buttons on screen to control relays

### ISSUE THREAD

**Issue by malvar0929** [zafersn/WiFi-RC-Controller-With-Camera#5]
Hello, 
I love your android app and I'm successfully controlling a lego pi-car I have built.
I'm wondering if there's a way to add touch buttons to the android app interface to control relays through the raspberry pi?
Any suggestions greatly appreciated. Thank you in advance.

**Comment by zafersn** [comment]
Hi @malvar0929 
Thank you so much. At the moment there is no such feature. But version 4 will also feature video recording, line follow (image processing), and video recording. Thank you for your interest.

  Good luck.

**Comment by malvar0929** [comment]
Sounds great. Looking forward to the new features.
