### ISSUE TITLE
Failed to start Avahi Stack and Hostname services

### ISSUE THREAD

**Issue by AWKT** [zafersn/WiFi-RC-Controller-With-Camera#8]
I really like you platform, thanks for developing it.  I installed V3 on a RPi 3 with built in WiFi and a second generation RPi camera module.   I can see the network and connect to it, but I cannot enable video.  I plugged the RPi into a monitor and watched the loading screen, the Avahi mDNS/DNS-SD Stack and Hostname Services failed to load.  I had a keyboard plugged in also, but the system seems to be stuck loading something, so I am not able to access the prompt to enter any commands.  Without being able to type commands, I don't know how to do any troubleshooting.  Do you have any suggestions?
![img_20170617_214413](https://user-images.githubusercontent.com/16865799/27266141-48f54870-546c-11e7-8a59-0887181322c2.jpg)

**Comment by zafersn** [comment]
hi @AWKT.  I am sorry to answer late to the question. The first action you made is correct. See what's on screen after connecting raspberry to a screen.  Wait until the time in the last row of 'A start job is running ... / 1min 33 s' is filled in according to the above picture.Once this period is over, the wifi broadcast must start automatically..After this step, send a command to the raspberries over the phone and observe that the commands you send come to the raspberries. If no command is received, configure your phone wifi.

**Comment by AWKT** [comment]
Thanks, I had previously used my phone with the RPi as a hotspot and streamed video, so I had assumed I did not need to configure the phone wifi.  I fixed it tonight and it worked great.  Thanks so much.

**Comment by zafersn** [comment]
I'm glad. Good luck.
