### ISSUE TITLE
raspery pi açılmıyor

### ISSUE THREAD

**Issue by BURAKOZ55** [zafersn/WiFi-RC-Controller-With-Camera#9]
biryerden sonra devamlı no serial port found yazısı akıp gidiyor

**Comment by zafersn** [comment]
Selam @BURAKOZ55  no serial port found hatası. Arduino takmadığından kaynaklanıyor. Arduino Da V1 ve V2 Sürümlerinde geçerli. V3 sürümünü kurmalı ve kullanmalısın, çünkü v3 sürümünün dışındaki sürümlerin android desteği kesildi.
